/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.vista;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import main.java.logica.DevolucionLogica;
import main.java.logica.ProductoLogica;
import main.java.logica.TransaccionLogica;
import main.java.logica.TransaccionProductoLogica;
import main.java.modelo.Devolucion;
import main.java.modelo.Producto;
import main.java.modelo.Transaccion;
import main.java.modelo.TransaccionProducto;

/**
 *
 * @author danri
 */
public class DevolucionView extends javax.swing.JPanel {

    /**
     * Creates new form DevolucionView
     */
    Transaccion transaccion;
    
    public DevolucionView() {
        initComponents();
        transaccion = new Transaccion();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRealizar = new javax.swing.JButton();
        jTextFieldNombreCliente = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLabelNombreCliente = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jTextFieldTipo = new javax.swing.JTextField();
        jLabelTipo = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTablaProductos = new javax.swing.JTable();

        jButtonRealizar.setText("Realizar");
        jButtonRealizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRealizarActionPerformed(evt);
            }
        });

        jTextFieldNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreClienteActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setPreferredSize(new java.awt.Dimension(65, 25));
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabelNombreCliente.setText("Nombre del cliente");

        jLabelFecha.setText("Fecha");

        jLabelTipo.setText("Tipo");

        jTableTablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Valor unitario", "Devolver", "IdProducto", "idTransaccionProducto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableTablaProductos);
        if (jTableTablaProductos.getColumnModel().getColumnCount() > 0) {
            jTableTablaProductos.getColumnModel().getColumn(3).setResizable(false);
            jTableTablaProductos.getColumnModel().getColumn(4).setMinWidth(0);
            jTableTablaProductos.getColumnModel().getColumn(4).setPreferredWidth(0);
            jTableTablaProductos.getColumnModel().getColumn(4).setMaxWidth(0);
            jTableTablaProductos.getColumnModel().getColumn(5).setMinWidth(0);
            jTableTablaProductos.getColumnModel().getColumn(5).setPreferredWidth(0);
            jTableTablaProductos.getColumnModel().getColumn(5).setMaxWidth(0);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldNombreCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNombreCliente, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelFecha)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabelTipo)
                            .addComponent(jTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jButtonRealizar)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreCliente)
                    .addComponent(jLabelFecha))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRealizar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        TransaccionLogica trLogica = new TransaccionLogica();
        
        List<Transaccion> transacciones = new ArrayList<>();
        
        try {
            transacciones = trLogica.buscarTransaccion(jTextFieldNombreCliente.getText(), jDateChooser1.getDate());
        } catch (Exception ex) {
            Logger.getLogger(DevolucionView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Object[] options = comboBoxPane(transacciones);
        JComboBox optionList = new JComboBox(options);
        
        if(sizeofTransacciones(transacciones) > 0){
           optionList.setSelectedIndex(transacciones.size()- 1);
           JOptionPane.showMessageDialog(null, optionList, "Selecciona una transacción",
               JOptionPane.QUESTION_MESSAGE);   
        }else{
            JOptionPane.showMessageDialog(this, "No se encontraron transacciones");
        }
        
        try {
            transaccion = trLogica.buscarTransaccion(transacciones.get(optionList.getSelectedIndex()).getId());
        } catch (Exception ex) {
            Logger.getLogger(DevolucionView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jTextFieldTipo.setText(transaccion.getTipo());
        cargarTabla(transaccion);
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    public int sizeofTransacciones(List<Transaccion> transacciones){
        return transacciones.size();
    }
    
    public void limpiarTabla(){
        DefaultTableModel tb = (DefaultTableModel) jTableTablaProductos.getModel();
        int a = jTableTablaProductos.getRowCount()-1;
        for (int i = a; i >= 0; i--) {           
            tb.removeRow(tb.getRowCount()-1);
        } 
    }
    
    public void cargarTabla(Transaccion transaccion){
        limpiarTabla();
        TransaccionProductoLogica trPL = new TransaccionProductoLogica();
        List<TransaccionProducto> listaProductos = trPL.listarProductosTransaccion(transaccion.getId());
        
        for (int i = 0; i < listaProductos.size(); i++) {
            ProductoLogica pL = new ProductoLogica();
            Producto producto = listaProductos.get(i).getIdProducto();
            
            DefaultTableModel modelo = (DefaultTableModel) jTableTablaProductos.getModel();
            Object filaNueva[] = {producto.getNombre() , listaProductos.get(i).getCantidad(), 
                listaProductos.get(i).getValorUnitario(), false, producto.getId(), 
                listaProductos.get(i).getId()};
            modelo.addRow(filaNueva); 
        }
    }
    
    public Object[] comboBoxPane(List<Transaccion> transacciones){
        Object[] options = new Object[transacciones.size()];
        
        for (int i = 0; i < transacciones.size(); i++) {
            DateFormat writeFormat = new SimpleDateFormat( "yyyy-MM-dd HH:mm:ss");
            Date date = transacciones.get(i).getFecha();
            String formattedDate = writeFormat.format(date);
            options[i] = transacciones.get(i).getNombreCliente() + ", " + transacciones.get(i).getTipo() +
                    ", " + formattedDate;
        }
        
        return options;
    }
    
    private void jButtonRealizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRealizarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTableTablaProductos.getModel();
        List<TransaccionProducto> listaTransaccionProducto = new ArrayList<>();
        TransaccionProductoLogica tpL = new TransaccionProductoLogica();
        
        for (int i = 0; i < modelo.getRowCount(); i++) {
            if(jTableTablaProductos.getValueAt(i, 3).toString().equals("true")){
                try {
                    TransaccionProducto transaccionProducto =
                            tpL.buscarTransaccionProducto(Integer.parseInt
                            (jTableTablaProductos.getValueAt(i, 5).toString()));
                    listaTransaccionProducto.add(transaccionProducto);
                } catch (Exception ex) {
                    Logger.getLogger(DevolucionView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
        try {
            if(listaTransaccionProducto.size() > 0){
                registrarDevolucion(listaTransaccionProducto);
            }else{
                JOptionPane.showMessageDialog(this, "Por favor seleccionar elementos");
            }
        } catch (Exception ex) {
            Logger.getLogger(DevolucionView.class.getName()).log(Level.SEVERE, null, ex);
        }
        limpiarTabla();
    }//GEN-LAST:event_jButtonRealizarActionPerformed

    public void registrarDevolucion(List<TransaccionProducto> listaTransaccionProducto) throws Exception{
        Devolucion devolucion = new Devolucion();
        DevolucionLogica dvL = new DevolucionLogica();
        Calendar calendar = new GregorianCalendar();
        Date date = calendar.getTime();
        
        for(int i = 0; i < listaTransaccionProducto.size(); i++){
            devolucion.setFecha(date);
            devolucion.setIdTransaccionProducto(listaTransaccionProducto.get(i));
            devolucion.setNombreCliente(jTextFieldNombreCliente.getText());
            dvL.registrarDevolucion(devolucion);   
        }
        JOptionPane.showMessageDialog(this, "Devolución exitosa");
    }
    
    private void jTextFieldNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonRealizar;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelNombreCliente;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableTablaProductos;
    private javax.swing.JTextField jTextFieldNombreCliente;
    private javax.swing.JTextField jTextFieldTipo;
    // End of variables declaration//GEN-END:variables
}
